version: '3'
services:
  vpn:
    image: n2n:alpine
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    network_mode: host
    entrypoint: ["dumb-init"]
    command: ["edge","-a192.168.100.10", "-lsupernode.ntop.org:7777", "-r","-f"]
    restart: "unless-stopped"
